### ISSUE TITLE
Housekeeper agent slows down the world

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpGameModifications#13]
![image](https://user-images.githubusercontent.com/26553592/39336516-3d57a69c-49b8-11e8-8c71-1a7509b4b7d9.png)

**Comment by Amaikokonut** [comment]
Yeeeah this agent definitely has _way_ too much going on in its timer script (like _all_ the Who's Wanted Registers). Short-term solutions for this include breaking it down into smaller agents with different timers and running the scripts over multiple ticks (which could result in the WWR missing/delaying some online/offline events but would probably still be preferable to a slow game). I think the best long-term option will probably end up being to _eventually_ get the client itself to check and trigger the WWR events, which it can probably do a lot faster than the CAOS (getting the client itself to trigger the immigrant checker would also take a load off the engine) but that's probably something to worry about once everything else is stable.

**Comment by Amaikokonut** [comment]
Since the WWR/Housekeeper split, this agent is running a bit more reasonably now. (The WWR might be another matter, but...ehh...)
