### ISSUE TITLE
In-game Error Display

### ISSUE THREAD

**Issue by Amaikokonut** [AlbianWarp/AlbianWarpGameModifications#21]
Display errors warping out a creature due to it already existing on disk in some form in a visible place (like on the workshop screen or portal notification)

**Comment by Amaikokonut** [comment]
This was added to the containment chamber script but I opted to not add portal notifications as it was really spammy. Instead the creature simply won't portal-warp and a notification is dbg: outs'd (same as when a creature can't warp due to travel sickness). 

Do you think figuring out how to display portal warp errors is still something the should be implemented before beta, or should this go back into the backlog?

**Comment by KeyboardInterrupt** [comment]
We can do this later on.
currently the client still outputs the DBG Messages anyway, so someon encountering the Issue will know what's up :)

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
